### PR TITLE
Adds tagged logging support and Logger::Formatter support

### PR DESCRIPTION
**Pull request by meltingice**
Builds on @mitnal's [PR](https://github.com/Graylog2/gelf-rb/pull/8), which adds tagged logging support, and also adds support for logger formatters.

``` ruby
# Example formatter.
# Unlike most formatters, message is a hash.
# Must return a hash as well.
class MyGelfFormatter < Logger::Formatter
  def call(severity, datetime, facility, message)
    message.merge({
      pid: Process.pid
    })
  end
end
```

``` ruby
config.log_tags = [:uuid, :remote_ip]
config.logger = GELF::Logger.new("localhost", 12201, 'LAN', {
  tags: [:uuid, :remote_ip] # same order as config.log_tags !
})

config.logger = MyGelfFormatter.new
```

### CODE REVIEW

**Comment by joschi** [comment]
@meltingice Would you mind cleaning up those commits a little bit and rebase to current master? There are some unintended changes in this PR, like the unresolved conflicts in `.travis.yml`.

**Comment by milgner** [comment]
Seems like this is partly a duplicate of #35 now. Also, besides history cleanup, would you mind creating separate PRs for formatter support and tagged logging?

**Comment by jalogisch** [comment]
@milgner I would like to close this PR - CLA is still beding and this is kind of outdated and might need some love.

How would you decide?

**Comment by jalogisch** [comment]
As if the missing CLA i'll close this PR now

**Pull request closed without merging**
