### PR TITLE
Make gelf compactable with ruby-2.4.0

### PR DESCRIPTION
**Pull request by tessie**
In ruby 2.4.0
  FixNum is deprciated 
Also  json (1.8.3) is not compatible with 2.4.0

### CODE REVIEW

**Comment by joschi** [comment]
@tessie Thanks for your contribution!

Please sign the CLA for this repository at https://cla-assistant.io/graylog-labs/gelf-rb?pullRequest=55 so that we can merge this PR.

Also, please add Ruby 2.4.0 to the `.travis.yml` file (build matrix) so that Travis CI will test this project with that Ruby version.

**Comment by tessie** [comment]
@joschi  I have actually signed the CLA agreement. But it is still showing pending. Can you please help me

**Comment by tessie** [comment]
Thanks @joschi  Signed the CLA also. There was an issue with email id associated with commit.This is fixed

**Comment by tessie** [comment]
:)

**Pull request merged**
